<?php

print "<!DOCTYPE html>\n";
print "<html lang=\"en\">\n";
print "   <head>\n";
print "      <meta charset=\"utf-8\">\n";
print "      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
print "      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n";
print "      <meta name=\"description\" content=\"Askbootstrap\">\n";
print "      <meta name=\"author\" content=\"Askbootstrap\">\n";
print "      <title>VIDOE - Video Streaming Website HTML Template</title>\n";
print "      <!-- Favicon Icon -->\n";
print "      <link rel=\"icon\" type=\"image/png\" href=\"img/favicon.png\">\n";
print "      <!-- Bootstrap core CSS-->\n";
print "      <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n";
print "      <!-- Custom fonts for this template-->\n";
print "      <link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n";
print "      <!-- Custom styles for this template-->\n";
print "      <link href=\"css/osahan.css\" rel=\"stylesheet\">\n";
print "      <!-- Owl Carousel -->\n";
print "      <link rel=\"stylesheet\" href=\"vendor/owl-carousel/owl.carousel.css\">\n";
print "      <link rel=\"stylesheet\" href=\"vendor/owl-carousel/owl.theme.css\">\n";
print "   </head>\n";
print "   <body id=\"page-top\">\n";
print "      <nav class=\"navbar navbar-expand navbar-light bg-white static-top osahan-nav sticky-top\">\n";
print "            \n";
print "         <button class=\"btn btn-link btn-sm text-secondary order-1 order-sm-0\" id=\"sidebarToggle\">\n";
print "         <i class=\"fas fa-bars\"></i>\n";
print "         </button>   \n";
print "         <a class=\"navbar-brand mr-1\" href=\"index.html\"><img class=\"img-fluid\" alt=\"\" src=\"img/logo.png\"></a>\n";
print "         <!-- Navbar Search -->\n";
print "         <form class=\"d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-5 my-2 my-md-0 osahan-navbar-search\">\n";
print "            <div class=\"input-group\">\n";
print "               <input type=\"text\" class=\"form-control\" placeholder=\"Search for...\">\n";
print "               <div class=\"input-group-append\">\n";
print "                  <button class=\"btn btn-light\" type=\"button\">\n";
print "                  <i class=\"fas fa-search\"></i> \n";
print "                  </button>\n";
print "               </div>\n";
print "            </div>\n";
print "         </form>\n";
print "         <!-- Navbar -->\n";
print "         <ul class=\"navbar-nav ml-auto ml-md-0 osahan-right-navbar\">\n";
print "            <li class=\"nav-item mx-1\">\n";
print "               <a class=\"nav-link\" href=\"upload.html\">\n";
print "               <i class=\"fas fa-plus-circle fa-fw\"></i>\n";
print "               Upload Video\n";
print "               </a>\n";
print "            </li>\n";
print "            <li class=\"nav-item dropdown no-arrow mx-1\">\n";
print "               <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n";
print "               <i class=\"fas fa-bell fa-fw\"></i>\n";
print "               <span class=\"badge badge-danger\">9+</span>\n";
print "               </a>\n";
print "               <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"alertsDropdown\">\n";
print "                  <a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-edit \"></i>   Action</a>\n";
print "                  <a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-headphones-alt \"></i>   Another action</a>\n";
print "                  <div class=\"dropdown-divider\"></div>\n";
print "                  <a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-star \"></i>   Something else here</a>\n";
print "               </div>\n";
print "            </li>\n";
print "            <li class=\"nav-item dropdown no-arrow mx-1\">\n";
print "               <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n";
print "               <i class=\"fas fa-envelope fa-fw\"></i>\n";
print "               <span class=\"badge badge-success\">7</span>\n";
print "               </a>\n";
print "               <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"messagesDropdown\">\n";
print "                  <a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-edit \"></i>   Action</a>\n";
print "                  <a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-headphones-alt \"></i>   Another action</a>\n";
print "                  <div class=\"dropdown-divider\"></div>\n";
print "                  <a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-star \"></i>   Something else here</a>\n";
print "               </div>\n";
print "            </li>\n";
print "            <li class=\"nav-item dropdown no-arrow osahan-right-navbar-user\">\n";
print "               <a class=\"nav-link dropdown-toggle user-dropdown-link\" href=\"#\" id=\"userDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n";
print "               <img alt=\"Avatar\" src=\"img/user.png\">\n";
print "               Osahan \n";
print "               </a>\n";
print "               <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"userDropdown\">\n";
print "                  <a class=\"dropdown-item\" href=\"account.html\"><i class=\"fas fa-fw fa-user-circle\"></i>   My Account</a>\n";
print "                  <a class=\"dropdown-item\" href=\"subscriptions.html\"><i class=\"fas fa-fw fa-video\"></i>   Subscriptions</a>\n";
print "                  <a class=\"dropdown-item\" href=\"settings.html\"><i class=\"fas fa-fw fa-cog\"></i>   Settings</a>\n";
print "                  <div class=\"dropdown-divider\"></div>\n";
print "                  <a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\" data-target=\"#logoutModal\"><i class=\"fas fa-fw fa-sign-out-alt\"></i>   Logout</a>\n";
print "               </div>\n";
print "            </li>\n";
print "         </ul>\n";
print "      </nav>\n";
print "      <div id=\"wrapper\">\n";
print "         <!-- Sidebar -->\n";
print "         <ul class=\"sidebar navbar-nav\">\n";
print "            <li class=\"nav-item active\">\n";
print "               <a class=\"nav-link\" href=\"index.html\">\n";
print "               <i class=\"fas fa-fw fa-home\"></i>\n";
print "               <span>Home</span>\n";
print "               </a>\n";
print "            </li>\n";
print "            <li class=\"nav-item\">\n";
print "               <a class=\"nav-link\" href=\"channels.html\">\n";
print "               <i class=\"fas fa-fw fa-users\"></i>\n";
print "               <span>Channels</span>\n";
print "               </a>\n";
print "            </li>\n";
print "            <li class=\"nav-item\">\n";
print "               <a class=\"nav-link\" href=\"single-channel.html\">\n";
print "               <i class=\"fas fa-fw fa-user-alt\"></i>\n";
print "               <span>Single Channel</span>\n";
print "               </a>\n";
print "            </li>\n";
print "            <li class=\"nav-item\">\n";
print "               <a class=\"nav-link\" href=\"video-page.html\">\n";
print "               <i class=\"fas fa-fw fa-video\"></i>\n";
print "               <span>Video Page</span>\n";
print "               </a>\n";
print "            </li>\n";
print "            <li class=\"nav-item\">\n";
print "               <a class=\"nav-link\" href=\"upload-video.html\">\n";
print "               <i class=\"fas fa-fw fa-cloud-upload-alt\"></i>\n";
print "               <span>Upload Video</span>\n";
print "               </a>\n";
print "            </li>\n";
print "            <li class=\"nav-item dropdown\">\n";
print "               <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n";
print "               <i class=\"fas fa-fw fa-folder\"></i>\n";
print "               <span>Pages</span>\n";
print "               </a>\n";
print "               <div class=\"dropdown-menu\">\n";
print "                  <h6 class=\"dropdown-header\">Login Screens:</h6>\n";
print "                  <a class=\"dropdown-item\" href=\"login.html\">Login</a>\n";
print "                  <a class=\"dropdown-item\" href=\"register.html\">Register</a>\n";
print "                  <a class=\"dropdown-item\" href=\"forgot-password.html\">Forgot Password</a>\n";
print "                  <div class=\"dropdown-divider\"></div>\n";
print "                  <h6 class=\"dropdown-header\">Other Pages:</h6>\n";
print "                  <a class=\"dropdown-item\" href=\"404.html\">404 Page</a>\n";
print "                  <a class=\"dropdown-item\" href=\"blank.html\">Blank Page</a>\n";
print "               </div>\n";
print "            </li>\n";
print "            <li class=\"nav-item\">\n";
print "               <a class=\"nav-link\" href=\"history-page.html\">\n";
print "               <i class=\"fas fa-fw fa-history\"></i>\n";
print "               <span>History Page</span>\n";
print "               </a>\n";
print "            </li>\n";
print "            <li class=\"nav-item dropdown\">\n";
print "               <a class=\"nav-link dropdown-toggle\" href=\"categories.html\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n";
print "               <i class=\"fas fa-fw fa-list-alt\"></i>\n";
print "               <span>Categories</span>\n";
print "               </a>\n";
print "               <div class=\"dropdown-menu\">\n";
print "                  <a class=\"dropdown-item\" href=\"categories.html\">Movie</a>\n";
print "                  <a class=\"dropdown-item\" href=\"categories.html\">Music</a>\n";
print "                  <a class=\"dropdown-item\" href=\"categories.html\">Television</a>\n";
print "               </div>\n";
print "            </li>\n";
print "            <li class=\"nav-item channel-sidebar-list\">\n";
print "               <h6>SUBSCRIPTIONS</h6>\n";
print "               <ul>\n";
print "                  <li>\n";
print "                     <a href=\"subscriptions.html\">\n";
print "                     <img class=\"img-fluid\" alt=\"\" src=\"img/s1.png\"> Your Life \n";
print "                     </a>\n";
print "                  </li>\n";
print "                  <li>\n";
print "                     <a href=\"subscriptions.html\">\n";
print "                     <img class=\"img-fluid\" alt=\"\" src=\"img/s2.png\"> Unboxing  <span class=\"badge badge-warning\">2</span>\n";
print "                     </a>\n";
print "                  </li>\n";
print "                  <li>\n";
print "                     <a href=\"subscriptions.html\">\n";
print "                     <img class=\"img-fluid\" alt=\"\" src=\"img/s3.png\"> Product / Service  \n";
print "                     </a>\n";
print "                  </li>\n";
print "                  <li>\n";
print "                     <a href=\"subscriptions.html\">\n";
print "                     <img class=\"img-fluid\" alt=\"\" src=\"img/s4.png\">  Gaming \n";
print "                     </a>\n";
print "                  </li>\n";
print "               </ul>\n";
print "            </li>\n";
print "         </ul>\n";
print "         <div class=\"single-channel-page\" id=\"content-wrapper\">\n";
print "            <div class=\"single-channel-image\">\n";
print "               <img class=\"img-fluid\" alt=\"\" src=\"img/channel-banner.png\">\n";
print "               <div class=\"channel-profile\">\n";
print "                  <img class=\"channel-profile-img\" alt=\"\" src=\"img/s2.png\">\n";
print "                  <div class=\"social hidden-xs\">\n";
print "                     Social  \n";
print "                     <a class=\"fb\" href=\"#\">Facebook</a>\n";
print "                     <a class=\"tw\" href=\"#\">Twitter</a>\n";
print "                     <a class=\"gp\" href=\"#\">Google</a>\n";
print "                  </div>\n";
print "               </div>\n";
print "            </div>\n";
print "            <div class=\"single-channel-nav\">\n";
print "               <nav class=\"navbar navbar-expand-lg navbar-light\">\n";
print "                  <a class=\"channel-brand\" href=\"#\">Osahan Channel <span title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Verified\"><i class=\"fas fa-check-circle text-success\"></i></span></a>\n";
print "                  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n";
print "                  <span class=\"navbar-toggler-icon\"></span>\n";
print "                  </button>\n";
print "                  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n";
print "                     <ul class=\"navbar-nav mr-auto\">\n";
print "                        <li class=\"nav-item active\">\n";
print "                           <a class=\"nav-link\" href=\"#\">Videos <span class=\"sr-only\">(current)</span></a>\n";
print "                        </li>\n";
print "                        <li class=\"nav-item\">\n";
print "                           <a class=\"nav-link\" href=\"#\">Playlist</a>\n";
print "                        </li>\n";
print "                        <li class=\"nav-item\">\n";
print "                           <a class=\"nav-link\" href=\"#\">Channels</a>\n";
print "                        </li>\n";
print "                        <li class=\"nav-item\">\n";
print "                           <a class=\"nav-link\" href=\"#\">Discussion</a>\n";
print "                        </li>\n";
print "                        <li class=\"nav-item\">\n";
print "                           <a class=\"nav-link\" href=\"#\">About</a>\n";
print "                        </li>\n";
print "                        <li class=\"nav-item dropdown\">\n";
print "                           <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n";
print "                           Donate\n";
print "                           </a>\n";
print "                           <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n";
print "                              <a class=\"dropdown-item\" href=\"#\">Action</a>\n";
print "                              <a class=\"dropdown-item\" href=\"#\">Another action</a>\n";
print "                              <div class=\"dropdown-divider\"></div>\n";
print "                              <a class=\"dropdown-item\" href=\"#\">Something else here</a>\n";
print "                           </div>\n";
print "                        </li>\n";
print "                     </ul>\n";
print "                     <form class=\"form-inline my-2 my-lg-0\">\n";
print "                        <input class=\"form-control form-control-sm mr-sm-1\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\"><button class=\"btn btn-outline-success btn-sm my-2 my-sm-0\" type=\"submit\"><i class=\"fas fa-search\"></i></button>     <button class=\"btn btn-outline-danger btn-sm\" type=\"button\">Subscribe <strong>1.4M</strong></button>\n";
print "                     </form>\n";
print "                  </div>\n";
print "               </nav>\n";
print "            </div>\n";
print "            <div class=\"container-fluid\">\n";
print "               <div class=\"video-block section-padding\">\n";
print "                  <div class=\"row\">\n";
print "                     <div class=\"col-md-12\">\n";
print "                        <div class=\"main-title\">\n";
print "                           <div class=\"btn-group float-right right-action\">\n";
print "                              <a href=\"#\" class=\"right-action-link text-gray\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n";
print "                              Sort by <i class=\"fa fa-caret-down\" aria-hidden=\"true\"></i>\n";
print "                              </a>\n";
print "                              <div class=\"dropdown-menu dropdown-menu-right\">\n";
print "                                 <a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-star\"></i>   Top Rated</a>\n";
print "                                 <a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-signal\"></i>   Viewed</a>\n";
print "                                 <a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-times-circle\"></i>   Close</a>\n";
print "                              </div>\n";
print "                           </div>\n";
print "                           <h6>Videos</h6>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                     <div class=\"col-xl-3 col-sm-6 mb-3\">\n";
print "                        <div class=\"video-card\">\n";
print "                           <div class=\"video-card-image\">\n";
print "                              <a class=\"play-icon\" href=\"#\"><i class=\"fas fa-play-circle\"></i></a>\n";
print "                              <a href=\"#\"><img class=\"img-fluid\" src=\"img/v1.png\" alt=\"\"></a>\n";
print "                              <div class=\"time\">3:50</div>\n";
print "                           </div>\n";
print "                           <div class=\"video-card-body\">\n";
print "                              <div class=\"video-title\">\n";
print "                                 <a href=\"#\">There are many variations of passages of Lorem</a>\n";
print "                              </div>\n";
print "                              <div class=\"video-page text-success\">\n";
print "                                 Education  <a title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" href=\"#\" data-original-title=\"Verified\"><i class=\"fas fa-check-circle text-success\"></i></a>\n";
print "                              </div>\n";
print "                              <div class=\"video-view\">\n";
print "                                 1.8M views  <i class=\"fas fa-calendar-alt\"></i> 11 Months ago\n";
print "                              </div>\n";
print "                           </div>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                     <div class=\"col-xl-3 col-sm-6 mb-3\">\n";
print "                        <div class=\"video-card\">\n";
print "                           <div class=\"video-card-image\">\n";
print "                              <a class=\"play-icon\" href=\"#\"><i class=\"fas fa-play-circle\"></i></a>\n";
print "                              <a href=\"#\"><img class=\"img-fluid\" src=\"img/v2.png\" alt=\"\"></a>\n";
print "                              <div class=\"time\">3:50</div>\n";
print "                           </div>\n";
print "                           <div class=\"video-card-body\">\n";
print "                              <div class=\"video-title\">\n";
print "                                 <a href=\"#\">There are many variations of passages of Lorem</a>\n";
print "                              </div>\n";
print "                              <div class=\"video-page text-success\">\n";
print "                                 Education  <a title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" href=\"#\" data-original-title=\"Verified\"><i class=\"fas fa-check-circle text-success\"></i></a>\n";
print "                              </div>\n";
print "                              <div class=\"video-view\">\n";
print "                                 1.8M views  <i class=\"fas fa-calendar-alt\"></i> 11 Months ago\n";
print "                              </div>\n";
print "                           </div>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                     <div class=\"col-xl-3 col-sm-6 mb-3\">\n";
print "                        <div class=\"video-card\">\n";
print "                           <div class=\"video-card-image\">\n";
print "                              <a class=\"play-icon\" href=\"#\"><i class=\"fas fa-play-circle\"></i></a>\n";
print "                              <a href=\"#\"><img class=\"img-fluid\" src=\"img/v3.png\" alt=\"\"></a>\n";
print "                              <div class=\"time\">3:50</div>\n";
print "                           </div>\n";
print "                           <div class=\"video-card-body\">\n";
print "                              <div class=\"video-title\">\n";
print "                                 <a href=\"#\">There are many variations of passages of Lorem</a>\n";
print "                              </div>\n";
print "                              <div class=\"video-page text-danger\">\n";
print "                                 Education  <a title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" href=\"#\" data-original-title=\"Unverified\"><i class=\"fas fa-frown text-danger\"></i></a>\n";
print "                              </div>\n";
print "                              <div class=\"video-view\">\n";
print "                                 1.8M views  <i class=\"fas fa-calendar-alt\"></i> 11 Months ago\n";
print "                              </div>\n";
print "                           </div>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                     <div class=\"col-xl-3 col-sm-6 mb-3\">\n";
print "                        <div class=\"video-card\">\n";
print "                           <div class=\"video-card-image\">\n";
print "                              <a class=\"play-icon\" href=\"#\"><i class=\"fas fa-play-circle\"></i></a>\n";
print "                              <a href=\"#\"><img class=\"img-fluid\" src=\"img/v4.png\" alt=\"\"></a>\n";
print "                              <div class=\"time\">3:50</div>\n";
print "                           </div>\n";
print "                           <div class=\"video-card-body\">\n";
print "                              <div class=\"video-title\">\n";
print "                                 <a href=\"#\">There are many variations of passages of Lorem</a>\n";
print "                              </div>\n";
print "                              <div class=\"video-page text-success\">\n";
print "                                 Education  <a title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" href=\"#\" data-original-title=\"Verified\"><i class=\"fas fa-check-circle text-success\"></i></a>\n";
print "                              </div>\n";
print "                              <div class=\"video-view\">\n";
print "                                 1.8M views  <i class=\"fas fa-calendar-alt\"></i> 11 Months ago\n";
print "                              </div>\n";
print "                           </div>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                     <div class=\"col-xl-3 col-sm-6 mb-3\">\n";
print "                        <div class=\"video-card\">\n";
print "                           <div class=\"video-card-image\">\n";
print "                              <a class=\"play-icon\" href=\"#\"><i class=\"fas fa-play-circle\"></i></a>\n";
print "                              <a href=\"#\"><img class=\"img-fluid\" src=\"img/v5.png\" alt=\"\"></a>\n";
print "                              <div class=\"time\">3:50</div>\n";
print "                           </div>\n";
print "                           <div class=\"video-card-body\">\n";
print "                              <div class=\"video-title\">\n";
print "                                 <a href=\"#\">There are many variations of passages of Lorem</a>\n";
print "                              </div>\n";
print "                              <div class=\"video-page text-success\">\n";
print "                                 Education  <a title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" href=\"#\" data-original-title=\"Verified\"><i class=\"fas fa-check-circle text-success\"></i></a>\n";
print "                              </div>\n";
print "                              <div class=\"video-view\">\n";
print "                                 1.8M views  <i class=\"fas fa-calendar-alt\"></i> 11 Months ago\n";
print "                              </div>\n";
print "                           </div>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                     <div class=\"col-xl-3 col-sm-6 mb-3\">\n";
print "                        <div class=\"video-card\">\n";
print "                           <div class=\"video-card-image\">\n";
print "                              <a class=\"play-icon\" href=\"#\"><i class=\"fas fa-play-circle\"></i></a>\n";
print "                              <a href=\"#\"><img class=\"img-fluid\" src=\"img/v6.png\" alt=\"\"></a>\n";
print "                              <div class=\"time\">3:50</div>\n";
print "                           </div>\n";
print "                           <div class=\"video-card-body\">\n";
print "                              <div class=\"video-title\">\n";
print "                                 <a href=\"#\">There are many variations of passages of Lorem</a>\n";
print "                              </div>\n";
print "                              <div class=\"video-page text-danger\">\n";
print "                                 Education  <a title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" href=\"#\" data-original-title=\"Unverified\"><i class=\"fas fa-frown text-danger\"></i></a>\n";
print "                              </div>\n";
print "                              <div class=\"video-view\">\n";
print "                                 1.8M views  <i class=\"fas fa-calendar-alt\"></i> 11 Months ago\n";
print "                              </div>\n";
print "                           </div>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                     <div class=\"col-xl-3 col-sm-6 mb-3\">\n";
print "                        <div class=\"video-card\">\n";
print "                           <div class=\"video-card-image\">\n";
print "                              <a class=\"play-icon\" href=\"#\"><i class=\"fas fa-play-circle\"></i></a>\n";
print "                              <a href=\"#\"><img class=\"img-fluid\" src=\"img/v7.png\" alt=\"\"></a>\n";
print "                              <div class=\"time\">3:50</div>\n";
print "                           </div>\n";
print "                           <div class=\"video-card-body\">\n";
print "                              <div class=\"video-title\">\n";
print "                                 <a href=\"#\">There are many variations of passages of Lorem</a>\n";
print "                              </div>\n";
print "                              <div class=\"video-page text-success\">\n";
print "                                 Education  <a title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" href=\"#\" data-original-title=\"Verified\"><i class=\"fas fa-check-circle text-success\"></i></a>\n";
print "                              </div>\n";
print "                              <div class=\"video-view\">\n";
print "                                 1.8M views  <i class=\"fas fa-calendar-alt\"></i> 11 Months ago\n";
print "                              </div>\n";
print "                           </div>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                     <div class=\"col-xl-3 col-sm-6 mb-3\">\n";
print "                        <div class=\"video-card\">\n";
print "                           <div class=\"video-card-image\">\n";
print "                              <a class=\"play-icon\" href=\"#\"><i class=\"fas fa-play-circle\"></i></a>\n";
print "                              <a href=\"#\"><img class=\"img-fluid\" src=\"img/v8.png\" alt=\"\"></a>\n";
print "                              <div class=\"time\">3:50</div>\n";
print "                           </div>\n";
print "                           <div class=\"video-card-body\">\n";
print "                              <div class=\"video-title\">\n";
print "                                 <a href=\"#\">There are many variations of passages of Lorem</a>\n";
print "                              </div>\n";
print "                              <div class=\"video-page text-success\">\n";
print "                                 Education  <a title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" href=\"#\" data-original-title=\"Verified\"><i class=\"fas fa-check-circle text-success\"></i></a>\n";
print "                              </div>\n";
print "                              <div class=\"video-view\">\n";
print "                                 1.8M views  <i class=\"fas fa-calendar-alt\"></i> 11 Months ago\n";
print "                              </div>\n";
print "                           </div>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                     <div class=\"col-xl-3 col-sm-6 mb-3\">\n";
print "                        <div class=\"video-card\">\n";
print "                           <div class=\"video-card-image\">\n";
print "                              <a class=\"play-icon\" href=\"#\"><i class=\"fas fa-play-circle\"></i></a>\n";
print "                              <a href=\"#\"><img class=\"img-fluid\" src=\"img/v1.png\" alt=\"\"></a>\n";
print "                              <div class=\"time\">3:50</div>\n";
print "                           </div>\n";
print "                           <div class=\"video-card-body\">\n";
print "                              <div class=\"video-title\">\n";
print "                                 <a href=\"#\">There are many variations of passages of Lorem</a>\n";
print "                              </div>\n";
print "                              <div class=\"video-page text-success\">\n";
print "                                 Education  <a title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" href=\"#\" data-original-title=\"Verified\"><i class=\"fas fa-check-circle text-success\"></i></a>\n";
print "                              </div>\n";
print "                              <div class=\"video-view\">\n";
print "                                 1.8M views  <i class=\"fas fa-calendar-alt\"></i> 11 Months ago\n";
print "                              </div>\n";
print "                           </div>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                     <div class=\"col-xl-3 col-sm-6 mb-3\">\n";
print "                        <div class=\"video-card\">\n";
print "                           <div class=\"video-card-image\">\n";
print "                              <a class=\"play-icon\" href=\"#\"><i class=\"fas fa-play-circle\"></i></a>\n";
print "                              <a href=\"#\"><img class=\"img-fluid\" src=\"img/v2.png\" alt=\"\"></a>\n";
print "                              <div class=\"time\">3:50</div>\n";
print "                           </div>\n";
print "                           <div class=\"video-card-body\">\n";
print "                              <div class=\"video-title\">\n";
print "                                 <a href=\"#\">There are many variations of passages of Lorem</a>\n";
print "                              </div>\n";
print "                              <div class=\"video-page text-success\">\n";
print "                                 Education  <a title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" href=\"#\" data-original-title=\"Verified\"><i class=\"fas fa-check-circle text-success\"></i></a>\n";
print "                              </div>\n";
print "                              <div class=\"video-view\">\n";
print "                                 1.8M views  <i class=\"fas fa-calendar-alt\"></i> 11 Months ago\n";
print "                              </div>\n";
print "                           </div>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                     <div class=\"col-xl-3 col-sm-6 mb-3\">\n";
print "                        <div class=\"video-card\">\n";
print "                           <div class=\"video-card-image\">\n";
print "                              <a class=\"play-icon\" href=\"#\"><i class=\"fas fa-play-circle\"></i></a>\n";
print "                              <a href=\"#\"><img class=\"img-fluid\" src=\"img/v3.png\" alt=\"\"></a>\n";
print "                              <div class=\"time\">3:50</div>\n";
print "                           </div>\n";
print "                           <div class=\"video-card-body\">\n";
print "                              <div class=\"video-title\">\n";
print "                                 <a href=\"#\">There are many variations of passages of Lorem</a>\n";
print "                              </div>\n";
print "                              <div class=\"video-page text-danger\">\n";
print "                                 Education  <a title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" href=\"#\" data-original-title=\"Unverified\"><i class=\"fas fa-frown text-danger\"></i></a>\n";
print "                              </div>\n";
print "                              <div class=\"video-view\">\n";
print "                                 1.8M views  <i class=\"fas fa-calendar-alt\"></i> 11 Months ago\n";
print "                              </div>\n";
print "                           </div>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                     <div class=\"col-xl-3 col-sm-6 mb-3\">\n";
print "                        <div class=\"video-card\">\n";
print "                           <div class=\"video-card-image\">\n";
print "                              <a class=\"play-icon\" href=\"#\"><i class=\"fas fa-play-circle\"></i></a>\n";
print "                              <a href=\"#\"><img class=\"img-fluid\" src=\"img/v4.png\" alt=\"\"></a>\n";
print "                              <div class=\"time\">3:50</div>\n";
print "                           </div>\n";
print "                           <div class=\"video-card-body\">\n";
print "                              <div class=\"video-title\">\n";
print "                                 <a href=\"#\">There are many variations of passages of Lorem</a>\n";
print "                              </div>\n";
print "                              <div class=\"video-page text-success\">\n";
print "                                 Education  <a title=\"\" data-placement=\"top\" data-toggle=\"tooltip\" href=\"#\" data-original-title=\"Verified\"><i class=\"fas fa-check-circle text-success\"></i></a>\n";
print "                              </div>\n";
print "                              <div class=\"video-view\">\n";
print "                                 1.8M views  <i class=\"fas fa-calendar-alt\"></i> 11 Months ago\n";
print "                              </div>\n";
print "                           </div>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                  </div>\n";
print "                  <nav aria-label=\"Page navigation example\">\n";
print "                     <ul class=\"pagination justify-content-center pagination-sm mb-0\">\n";
print "                        <li class=\"page-item disabled\">\n";
print "                           <a tabindex=\"-1\" href=\"#\" class=\"page-link\">Previous</a>\n";
print "                        </li>\n";
print "                        <li class=\"page-item active\"><a href=\"#\" class=\"page-link\">1</a></li>\n";
print "                        <li class=\"page-item\"><a href=\"#\" class=\"page-link\">2</a></li>\n";
print "                        <li class=\"page-item\"><a href=\"#\" class=\"page-link\">3</a></li>\n";
print "                        <li class=\"page-item\">\n";
print "                           <a href=\"#\" class=\"page-link\">Next</a>\n";
print "                        </li>\n";
print "                     </ul>\n";
print "                  </nav>\n";
print "               </div>\n";
print "            </div>\n";
print "            <!-- /.container-fluid -->\n";
print "            <!-- Sticky Footer -->\n";
print "            <footer class=\"sticky-footer ml-0\">\n";
print "               <div class=\"container\">\n";
print "                  <div class=\"row no-gutters\">\n";
print "                     <div class=\"col-lg-6 col-sm-6\">\n";
print "                        <p class=\"mt-1 mb-0\">© Copyright 2018 <strong class=\"text-dark\">Vidoe</strong>. All Rights Reserved<br>\n";
print "                           <small class=\"mt-0 mb-0\">Made with <i class=\"fas fa-heart text-danger\"></i> by <a class=\"text-primary\" target=\"_blank\" href=\"https://askbootstrap.com/\">Ask Bootstrap</a>\n";
print "                           </small>\n";
print "                        </p>\n";
print "                     </div>\n";
print "                     <div class=\"col-lg-6 col-sm-6 text-right\">\n";
print "                        <div class=\"app\">\n";
print "                           <a href=\"#\"><img alt=\"\" src=\"img/google.png\"></a>\n";
print "                           <a href=\"#\"><img alt=\"\" src=\"img/apple.png\"></a>\n";
print "                        </div>\n";
print "                     </div>\n";
print "                  </div>\n";
print "               </div>\n";
print "            </footer>\n";
print "         </div>\n";
print "         <!-- /.content-wrapper -->\n";
print "      </div>\n";
print "      <!-- /#wrapper -->\n";
print "      <!-- Scroll to Top Button-->\n";
print "      <a class=\"scroll-to-top rounded\" href=\"#page-top\">\n";
print "      <i class=\"fas fa-angle-up\"></i>\n";
print "      </a>\n";
print "      <!-- Logout Modal-->\n";
print "      <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n";
print "         <div class=\"modal-dialog modal-sm modal-dialog-centered\" role=\"document\">\n";
print "            <div class=\"modal-content\">\n";
print "               <div class=\"modal-header\">\n";
print "                  <h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\n";
print "                  <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n";
print "                  <span aria-hidden=\"true\">×</span>\n";
print "                  </button>\n";
print "               </div>\n";
print "               <div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>\n";
print "               <div class=\"modal-footer\">\n";
print "                  <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\n";
print "                  <a class=\"btn btn-primary\" href=\"login.html\">Logout</a>\n";
print "               </div>\n";
print "            </div>\n";
print "         </div>\n";
print "      </div>\n";
print "      <!-- Bootstrap core JavaScript-->\n";
print "      <script src=\"vendor/jquery/jquery.min.js\"></script>\n";
print "      <script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n";
print "      <!-- Core plugin JavaScript-->\n";
print "      <script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\n";
print "      <!-- Owl Carousel -->\n";
print "      <script src=\"vendor/owl-carousel/owl.carousel.js\"></script>\n";
print "      <!-- Custom scripts for all pages-->\n";
print "      <script src=\"js/custom.js\"></script>\n";
print "   </body>\n";
print "</html>";

?>
